[package]
name = "consumer"
version = "0.1.0"
edition = "2024"

[dependencies]
async-global-executor = "3.1.0"
futures-lite = "2.6.1"
futures-util = "0.3.31"
lapin = "3.7.2"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
